sudo: false
language: ruby
rvm:
  - ruby-head
  - 2.4.2
  - 2.3.5
  - 2.2.8
  - jruby-head
  - jruby-9.1.13.0
  - jruby-9.0.5.0
env:
  - RACK_VERSION='~> 2.0.0'
before_install: gem install bundler -v 1.15.4
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
