sudo: false
language: ruby
rvm:
  - ruby-head
  - 2.5.1
  - 2.4.4
  - 2.3.7
  - jruby-head
  - jruby-9.2.0.0
  - jruby-9.1.17.0
env:
  - RACK_VERSION='~> 2.0.0'
before_install: gem install bundler -v 1.16.4
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
