sudo: false
language: ruby
rvm:
  - ruby-head
  - 2.4.2
  - 2.3.5
  - 2.2.8
  - 2.1.10
  - 2.0.0-p648
  - 1.9.3-p551
  - jruby-head
  - jruby-9.1.13.0
  - jruby-1.7.27
env:
  - RACK_VERSION='~> 2.0.0'
  - RACK_VERSION='~> 1.6.8'
  - RACK_VERSION='~> 1.5.5'
  - RACK_VERSION='~> 1.4.7'
before_install: gem install bundler -v 1.15.4
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  exclude:
    - rvm: 2.1.10
      env: RACK_VERSION='~> 2.0.0'
    - rvm: 2.0.0-p648
      env: RACK_VERSION='~> 2.0.0'
    - rvm: 1.9.3-p551
      env: RACK_VERSION='~> 2.0.0'
    - rvm: jruby-1.7.27
      env: RACK_VERSION='~> 2.0.0'
